import type { Metadata } from 'next';
import { Anton } from 'next/font/google';
import './globals.css';
import SmoothScrollWrapper from './component/SmoothScrollWrapper';

const anton = Anton({
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${anton.className} antialiased`}>
        <SmoothScrollWrapper>{children}</SmoothScrollWrapper>
      </body>
    </html>
  );
}
